/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dk_aau_d101f14_tinyvm_TinyNativeInterface */

#ifndef _Included_dk_aau_d101f14_tinyvm_TinyNativeInterface
#define _Included_dk_aau_d101f14_tinyvm_TinyNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dk_aau_d101f14_tinyvm_TinyNativeInterface
 * Method:    execute
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Integer;)Ljava/lang/Integer;
 */
JNIEXPORT jint JNICALL Java_dk_aau_d101f14_tinyvm_TinyNativeInterface_execute
  (JNIEnv *, jobject, jstring, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
